name: Pytest with Pycodestyle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run:  pip install -r requirements.txt
    - name: Test with pytest
      run:
        pytest -v --pycodestyl test_weight_entry.py